version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0
workflows:
  version: 2
  workflow:
    jobs:
      - build-and-publish

jobs:
  build-and-publish:
    working_directory: ~/project
    docker:
      - image: cimg/openjdk:8.0.322-browsers
    environment:
      JVM_OPTIONS: -Xmx1024M -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=512M
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx3840m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/node_modules
            - ~/.m2
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew clean build jacocoTestReport  --no-daemon
          no_output_timeout: 900s
          environment:
            _JAVA_OPTIONS: -Xmx1024M -XX:ReservedCodeCacheSize=512M
      - codecov/upload
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            mkdir -p ~/reports/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
            cp -R springfox-grails-contract-tests/build/reports/tests ~/reports
          when: always
      - store_test_results:
          path: build/reports/tests
      - store_test_results:
          path: build/test-results/test
      - run:
          name: Publish to artifactory
          command: ./gradlew artifactoryPublish --no-daemon -Dartifactory_repo_key=dcebotarenco-libs-snapshot
          no_output_timeout: 900s

